### PR TITLE
Fix style functionality regressions

### LINKED ISSUE #6: Regression in the clear completed button
In the old UI we used to show the number of items that were completed in the clear completed button

In the new UI we now longer show this
screen shot 2015-03-25 at 5 22 08 pm

There are tests around this behavior and those tests are now failing on all of the apps that have upgraded, this is something that we should fix

### PR DESCRIPTION
**Pull request by samccone**
Fixes #6
Fixes https://github.com/tastejs/todomvc/issues/1215

### CODE REVIEW

**Comment by samccone** [comment]
This also fixes the failing specs across all the new updated apps.

screen shot 2015-03-25 at 5 45 41 pm

**Comment by sindresorhus** [comment]
So, this was actually intentional. I wanted to get rid of the counter as it's not very useful and doesn't look very good UI wise, and the fastest way to do that was with a CSS hack rather than having to change all the apps.

**Comment by arthurvr** [comment]
> I wanted to get rid of the counter as it's not very useful and doesn't look very good UI wise

> I don't understand how the tests are affected by a CSS change though. The HTML is still the same...

cc @ColinEberhardt but I think the tests test for visibility.

**Comment by arthurvr** [comment]
> I wanted to get rid of the counter as it's not very useful and doesn't look very good UI wise

I agree with that, but the app spec should be updated, then.

> and the fastest way to do that was with a CSS hack rather than having to change all the apps.


On the long run we will just get rid of it anyways right?

**Comment by samccone** [comment]
correct the HTML is the same but the elements text is now hidden and replaced with css `content:` which causes the tests to fail (speaking from a fair bit of selenium experience here). 

I think we should revert this change, and add a new ticket to make a pass after the new UI is in all the apps to make this functional change because in the end this is a spec change that removes functionality. 

just my 2 cents though

**Comment by arthurvr** [comment]
> think we should revert this change, and add a new ticket to make a pass after the new UI is in all the apps to make this functional change because in the end this is a spec change that removes functionality.

+1. I agree that it should get removed but it should be done in a proper way (by actually updating the apps)

**Comment by samccone** [comment]
:+1:

**Comment by sindresorhus** [comment]
We can land this as it only applies to the 2.0 version, which means new apps.

@arthurvr Can you open a ticket about removing it from existing apps?

**Comment by samccone** [comment]
@sindresorhus can we get a point bump in package.json so we can go an update all the apps so the tests start to pass again :)

**Pull request merged**
