### PR TITLE
add pointer cursor style to button

### PR DESCRIPTION
**Pull request by owenyang0**
Much appreciated for all the recommendations of you. A pull request with descriptions is nice.
Yup, as @passy said above,
> a pointer over the destroy buttons would be more consistent with the other interactive elements on the page.

Thanks

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? Please include a description when you do a PR ;)

**Comment by passy** [comment]
Yup, descriptions are nice. :)

That said, I think a `pointer` over the destroy buttons would be more consistent with the other interactive elements on the page.

**Comment by addyosmani** [comment]
:+1: for landing this. For historical context though, we should definitely have some some description before this gets changed.

**Comment by sindresorhus** [comment]
:-1: I think the `pointer` is abused a lot. It has always been intended for links, not for anything clickable. We don't have a `pointer` on the todo toggle button either.

https://css-tricks.com/snippets/css/give-clickable-elements-a-pointer-cursor/#comment-169048

**Comment by arthurvr** [comment]
I am also :-1:. Totally agree with the above.

**Comment by passy** [comment]
Convincing comment!

**Pull request closed without merging**
