### PR TITLE
font-smoothing property doesn't exist

### PR DESCRIPTION
**Pull request by kasperpeulen**
Also in firefox you have to write:
-moz-osx-font-smoothing: grayscale;

### CODE REVIEW

**Comment by samccone** [comment]
yep :+1:

**Comment by sindresorhus** [comment]
Can you use correct indentation? Look at the diff.

**Comment by kasperpeulen** [comment]
@sindresorhus ooopz, fixed now

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request closed without merging**
